version: 1
frontend:
  phases:
    preBuild:
      commands:
        # Install root dependencies first (for monorepo workspace)
        - npm ci
        # Then install frontend dependencies
        - cd frontend
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # For Next.js 15 with static export
    # Output is in frontend/out from repository root
    baseDirectory: frontend/out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - frontend/node_modules/**/*
