version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # For Next.js 15 with static export
    # Build runs in frontend/, so output is in out/ (relative)
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - frontend/node_modules/**/*
