version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend
        - nvm use 24
        - node --version
        - npm --version
        - rm -rf node_modules package-lock.json
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    # For Next.js 15 with static export
    # Output is in frontend/out from repository root
    baseDirectory: frontend/out
    files:
      - '**/*'
  cache:
    paths: []
